name: tagをつける

on:
  push:
    branches:
      - *

jobs:
  add-tag:
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v1
      - name: ブランチ名を取得して、stepにidを付与
        run: echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: ワークフローをトリガーしたコミットSHAはGITHUB_REF
        run: echo ${GITHUB_REF}
