name: DockerImageをBuildしてECRへpushするやつ

on:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    steps:
      - name: AWS Credentialsの設定
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Amazon ECRへログイン
        uses: aws-actions/amazon-ecr-login@v1
      - name: リポジトリをcheckout
        uses: actions/checkout@v1
      - name: ブランチ名を取得して、stepにidを付与
        run: echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: BuildしてECRへpush
        env:
          AWS_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          CURRENT_BRANCH: ${{ steps.extract_branch.outputs.branch_name }}
          DOCKER_IMAGE: ${{ secrets.AWS_ECR_REPO_NAME }}
        run: bash ./build.sh | tail -1 | bash ./push-to-ecr.sh ${{ secrets.AWS_ECR_REPO_NAME }}
