name: Branch名を利用したDockerのイメージをビルドするだけ(意味ない)

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  build-only:
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v1
      - name: TimeZoneをGET
        run: apt-get update && apt-get install -y tzdata
      - name: ブランチ名を取得して、stepにidを付与
        run: echo "##[set-output name=branch_name;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: ビルド
        env:
          CURRENT_BRANCH: ${{ steps.extract_branch.outputs.branch_name }}
        run: |
          bash ./build.sh
          echo "=========="
          docker images ls
          echo "=========="
