name: Build and Push

on:
  push:
    branches:
      - feature/push-docker-image-to-ecr

jobs:
  build-and-push:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1
    - name: aws configure
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Amazon ECRへログイン
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: 出力！！
      run: |
        echo "==============================="
        echo ${{ steps.login-ecr.outputs.registry }}
        echo "==============================="
